package com.java.tp.boat.rental.utils.mappers;

import org.springframework.stereotype.Component;

import com.java.tp.boat.rental.exceptions.boat.BoatDoesNotExistException;
import com.java.tp.boat.rental.exceptions.client.ClientDoesNotExistException;
import com.java.tp.boat.rental.exceptions.reservation.ClientHasNoLicenseException;
import com.java.tp.boat.rental.exceptions.reservation.ReservationForTooManyPeopleException;
import com.java.tp.boat.rental.exceptions.reservation.ReservationStartIsAfterEndException;
import com.java.tp.boat.rental.model.business.Boat;
import com.java.tp.boat.rental.model.entity.BoatEntity;
import com.java.tp.boat.rental.model.entity.BoatTypes;
import com.java.tp.boat.rental.model.request.BoatCreationRequest;
import com.java.tp.boat.rental.model.request.BoatUpdateRequest;
import com.java.tp.boat.rental.model.response.BoatResponse;

@Component
public class BoatMapper implements Mapper<Boat, BoatEntity, BoatCreationRequest, BoatUpdateRequest, BoatResponse> {
    /*
     * Mapper interface for converting between different representations of a Boat.
     * 
     * BoatRequest -> Boat (Domain Model) -> BoatEntity (Database Entity) -> BoatResponse (API Response)
     */
    
    public BoatTypes toBoatType(String type) {
        try {
            return BoatTypes.valueOf(type.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(String.format("Invalid boat type: %s", type));
        }
    }

    public Boat toDomainFromRequestCreation(BoatCreationRequest boatRequest) {
        Boat boat = new Boat(
            boatRequest.getBid(),
            boatRequest.getName(),
            toBoatType(boatRequest.getType()),
            boatRequest.getMaxCapacity(),
            boatRequest.getLength(),
            boatRequest.getDailyRate(),
            boatRequest.getDeposit(),
            boatRequest.getNeedsLicense()
        );
        return boat;
    }

    public Boat toDomainFromEntity(BoatEntity boatEntity) {
        Boat boat = new Boat(
            boatEntity.getBid(),
            boatEntity.getName(),
            boatEntity.getType(),
            boatEntity.getMaxCapacity(),
            boatEntity.getLength(),
            boatEntity.getDailyRate(),
            boatEntity.getDeposit(),
            boatEntity.getNeedsLicense()
        );
        return boat;
    }

    public BoatEntity toEntityFromDomain(Boat boat) {
        BoatEntity boatEntity = new BoatEntity(); // for the id to be generated by the database
        boatEntity.setBid(boat.getBid());
        boatEntity.setName(boat.getName());
        boatEntity.setType(boat.getType());
        boatEntity.setMaxCapacity(boat.getMaxCapacity());
        boatEntity.setLength(boat.getLength());
        boatEntity.setDailyRate(boat.getDailyRate());
        boatEntity.setDeposit(boat.getDeposit());
        boatEntity.setNeedsLicense(boat.getNeedsLicense());
        return boatEntity;
    }

    public BoatResponse toResponseFromDomain(Boat boat) {
        BoatResponse boatResponse = new BoatResponse(
            boat.getBid(),
            boat.getName(),
            boat.getType().name(),
            boat.getMaxCapacity(),
            boat.getLength(),
            boat.getDailyRate(),
            boat.getDeposit(),
            boat.getNeedsLicense()
        );
        return boatResponse;
    }

    public BoatResponse toResponseFromEntity(BoatEntity boat) {
        BoatResponse boatResponse = new BoatResponse(
            boat.getBid(),
            boat.getName(),
            boat.getType().name(),
            boat.getMaxCapacity(),
            boat.getLength(),
            boat.getDailyRate(),
            boat.getDeposit(),
            boat.getNeedsLicense()
        );
        return boatResponse;
    }

    public BoatCreationRequest toRequestCreationFromRequestUpdate(BoatUpdateRequest boat) {
        BoatCreationRequest boatRequest = new BoatCreationRequest();
        boatRequest.setBid(boat.getBid());
        boatRequest.setName(boat.getName());
        boatRequest.setType(boat.getType());
        boatRequest.setMaxCapacity(boat.getMaxCapacity());
        boatRequest.setLength(boat.getLength());
        boatRequest.setDailyRate(boat.getDailyRate());
        boatRequest.setDeposit(boat.getDeposit());
        boatRequest.setNeedsLicense(boat.getNeedsLicense());
        return boatRequest;
    }

    @Override
    public Boat toDomainFromRequestUpdate(BoatUpdateRequest requestUpdate) throws ClientHasNoLicenseException, ReservationForTooManyPeopleException, ClientDoesNotExistException, BoatDoesNotExistException, ReservationStartIsAfterEndException {
        Boat boat = new Boat(
            requestUpdate.getBid(),
            requestUpdate.getName(),
            toBoatType(requestUpdate.getType()),
            requestUpdate.getMaxCapacity(),
            requestUpdate.getLength(),
            requestUpdate.getDailyRate(),
            requestUpdate.getDeposit(),
            requestUpdate.getNeedsLicense()
        );
        return boat;

    }
}
