package com.java.tp.boat.rental.utils.mappers;

import org.springframework.stereotype.Component;

import com.java.tp.boat.rental.model.business.Client;
import com.java.tp.boat.rental.model.entity.ClientEntity;
import com.java.tp.boat.rental.model.request.ClientCreationRequest;
import com.java.tp.boat.rental.model.request.ClientUpdateRequest;
import com.java.tp.boat.rental.model.response.ClientResponse;

@Component
public class ClientMapper implements Mapper<Client, ClientEntity, ClientCreationRequest, ClientUpdateRequest, ClientResponse> {
    /*
     * Mapper interface for converting between different representations of a Client.
     * 
     * ClientRequest -> Client (Domain Model) -> ClientEntity (Database Entity) -> ClientResponse (API Response)
     */
    
    public Client toDomainFromRequestCreation(ClientCreationRequest clientRequest) {
        Client client = new Client(
            clientRequest.getCid(),
            clientRequest.getFirstName(),
            clientRequest.getLastName(),
            clientRequest.getEmail(),
            clientRequest.getPhoneNumber(),
            clientRequest.getHasLicense()
        );
        return client;
    }

    public Client toDomainFromEntity(ClientEntity clientEntity) {
        Client client = new Client(
            clientEntity.getCid(),
            clientEntity.getFirstName(),
            clientEntity.getLastName(),
            clientEntity.getEmail(),
            clientEntity.getPhoneNumber(),
            clientEntity.getHasLicense()
        );
        return client;
    }

    public ClientEntity toEntityFromDomain(Client client) {
        ClientEntity clientEntity = new ClientEntity(); // for the id to be generated by the database
        clientEntity.setFirstName(client.getFirstName());
        clientEntity.setLastName(client.getLastName());
        clientEntity.setEmail(client.getEmail());
        clientEntity.setPhoneNumber(client.getPhoneNumber());
        clientEntity.setHasLicense(client.getHasLicense());
        return clientEntity;
    }

    public ClientEntity toEntityFromDomainWithId(Client client) {
        ClientEntity clientEntity = new ClientEntity();
        clientEntity.setCid(client.getCid()); // quand on veux plutot UPDATE que CREATE, on veut garder le meme id
        clientEntity.setFirstName(client.getFirstName());
        clientEntity.setLastName(client.getLastName());
        clientEntity.setEmail(client.getEmail());
        clientEntity.setPhoneNumber(client.getPhoneNumber());
        clientEntity.setHasLicense(client.getHasLicense());
        return clientEntity;
    }

    public ClientResponse toResponseFromDomain(Client client) {
        ClientResponse clientResponse = new ClientResponse(
            client.getCid(),
            client.getFirstName(),
            client.getLastName(),
            client.getEmail(),
            client.getPhoneNumber(),
            client.getHasLicense()
        );
        return clientResponse;
    }

    public ClientResponse toResponseFromEntity(ClientEntity client) {
        ClientResponse clientResponse = new ClientResponse(
            client.getCid(),
            client.getFirstName(),
            client.getLastName(),
            client.getEmail(),
            client.getPhoneNumber(),
            client.getHasLicense()
        );
        return clientResponse;
    }

    public ClientCreationRequest toRequestCreationFromRequestUpdate(ClientUpdateRequest client) {
        ClientCreationRequest clientRequest = new ClientCreationRequest();
        clientRequest.setFirstName(client.getFirstName());
        clientRequest.setLastName(client.getLastName());
        clientRequest.setEmail(client.getEmail());
        clientRequest.setPhoneNumber(client.getPhoneNumber());
        clientRequest.setHasLicense(client.getHasLicense());
        return clientRequest;
    }

    @Override
    public Client toDomainFromRequestUpdate(ClientUpdateRequest requestUpdate) {
        Client client = new Client(
            requestUpdate.getCid(),
            requestUpdate.getFirstName(),
            requestUpdate.getLastName(),
            requestUpdate.getEmail(),
            requestUpdate.getPhoneNumber(),
            requestUpdate.getHasLicense()
        );
        return client;

    }
}
