package com.java.tp.boat.rental.utils.mappers;

import org.springframework.stereotype.Component;

import com.java.tp.boat.rental.model.business.Client;
import com.java.tp.boat.rental.model.entity.ClientEntity;
import com.java.tp.boat.rental.model.request.ClientRequest;
import com.java.tp.boat.rental.model.response.ClientResponse;

@Component
public class ClientMapper {
    /*
     * Mapper interface for converting between different representations of a Client.
     * 
     * ClientRequest -> Client (Domain Model) -> ClientEntity (Database Entity) -> ClientResponse (API Response)
     */
    
    public Client toDomain(ClientRequest clientRequest) {
        Client client = new Client(
            clientRequest.getCid(),
            clientRequest.getFirstName(),
            clientRequest.getLastName(),
            clientRequest.getEmail(),
            clientRequest.getPhoneNumber(),
            clientRequest.getHasLicense()
        );
        return client;
    }

    public Client toDomain(ClientEntity clientEntity) {
        Client client = new Client(
            clientEntity.getCid(),
            clientEntity.getFirstName(),
            clientEntity.getLastName(),
            clientEntity.getEmail(),
            clientEntity.getPhoneNumber(),
            clientEntity.getHasLicense()
        );
        return client;
    }

    public ClientEntity toEntity(Client client) {
        ClientEntity clientEntity = new ClientEntity(); // for the id to be generated by the database
        clientEntity.setFirstName(client.getFirstName());
        clientEntity.setLastName(client.getLastName());
        clientEntity.setEmail(client.getEmail());
        clientEntity.setPhoneNumber(client.getPhoneNumber());
        clientEntity.setHasLicense(client.getHasLicense());
        return clientEntity;
    }

    public ClientResponse toResponse(Client client) {
        ClientResponse clientResponse = new ClientResponse(
            client.getCid(),
            client.getFirstName(),
            client.getLastName(),
            client.getEmail(),
            client.getPhoneNumber(),
            client.getHasLicense()
        );
        return clientResponse;
    }

    public ClientResponse toResponse(ClientEntity client) {
        ClientResponse clientResponse = new ClientResponse(
            client.getCid(),
            client.getFirstName(),
            client.getLastName(),
            client.getEmail(),
            client.getPhoneNumber(),
            client.getHasLicense()
        );
        return clientResponse;
    }
}
