package com.java.tp.boat.rental.utils.mappers;

import org.springframework.stereotype.Component;

import com.java.tp.boat.rental.model.business.Client;
import com.java.tp.boat.rental.model.business.Boat;
import com.java.tp.boat.rental.model.business.Reservation;
import com.java.tp.boat.rental.model.entity.BoatEntity;
import com.java.tp.boat.rental.model.entity.ClientEntity;
import com.java.tp.boat.rental.model.entity.ReservationEntity;
import com.java.tp.boat.rental.model.request.ReservationCreationRequest;
import com.java.tp.boat.rental.model.request.ReservationUpdateRequest;
import com.java.tp.boat.rental.model.response.ReservationResponse;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@Component
@AllArgsConstructor
public class ReservationMapper {

    /*
     * Mapper interface for converting between different representations of a Reservation.
     * 
     * ReservationRequest -> Reservation (Domain Model) -> ReservationEntity (Database Entity) -> ReservationResponse (API Response)
     */

    private ClientMapper clientMapper;
    private BoatMapper boatMapper;

    public Reservation toDomainFromRequestCreation(ReservationCreationRequest requestCreation, Client client, Boat boat) {
        Reservation reservation = new Reservation(
            requestCreation.getRid(),
            client,
            boat,
            requestCreation.getAmountOfPeople(),
            requestCreation.getStartTime(),
            requestCreation.getEndTime()
        );
        return reservation;
    }

    public Reservation toDomainFromEntity(ReservationEntity entity, Client client, Boat boat) {
        Reservation reservation = Reservation.fromEntity(
            entity.getRid(),
            client,
            boat,
            entity.getAmountOfPeople(),
            entity.getPrice(),
            entity.getDeposit(),
            entity.getStatus(),
            entity.getStartTime(),
            entity.getEndTime()
        );
        return reservation;
    }

    public ReservationEntity toEntityFromDomain(Reservation model, ClientEntity clientEntity, BoatEntity boatEntity) {
        ReservationEntity reservationEntity = new ReservationEntity(); // for the id to be generated by the database
        reservationEntity.setCid(clientEntity);
        reservationEntity.setBid(boatEntity);
        reservationEntity.setAmountOfPeople(model.getAmountOfPeople());
        reservationEntity.setPrice(model.getPrice());
        reservationEntity.setDeposit(model.getDeposit());
        reservationEntity.setStartTime(model.getStartTime());
        reservationEntity.setEndTime(model.getEndTime());
        return reservationEntity;
    }

    public ReservationResponse toResponseFromDomain(Reservation model) {
        ReservationResponse reservationResponse = new ReservationResponse(
            model.getRid(),
            model.getClient(),
            model.getBoat(),
            model.getAmountOfPeople(),
            model.getReservationStatus().name(),
            model.getStartTime(),
            model.getEndTime()
        );
        return reservationResponse;
    }

    public ReservationResponse toResponseFromEntity(ReservationEntity entity, Client client, Boat boat) {
        ReservationResponse reservationResponse = new ReservationResponse(
            entity.getRid(),
            client,
            boat,
            entity.getAmountOfPeople(),
            entity.getStatus().name(),
            entity.getStartTime(),
            entity.getEndTime()
        );
        return reservationResponse;
    }

    public ReservationCreationRequest toRequestCreationFromRequestUpdate(ReservationUpdateRequest requestUpdate) {
        ReservationCreationRequest reservationCreationRequest = new ReservationCreationRequest();
        reservationCreationRequest.setRid(requestUpdate.getRid());
        reservationCreationRequest.setCid(requestUpdate.getCid());
        reservationCreationRequest.setBid(requestUpdate.getBid());
        reservationCreationRequest.setAmountOfPeople(requestUpdate.getAmountOfPeople());
        reservationCreationRequest.setStartTime(requestUpdate.getStartTime());
        reservationCreationRequest.setEndTime(requestUpdate.getEndTime());
        return reservationCreationRequest;
    }

    public Reservation toDomainFromRequestUpdate(ReservationUpdateRequest requestUpdate, Client client, Boat boat) {
        Reservation reservation = Reservation.fromRequest(
            client,
            boat,
            requestUpdate.getAmountOfPeople(),
            requestUpdate.getStartTime(),
            requestUpdate.getEndTime()
        );
        return reservation;
    }

    public ReservationEntity toEntityFromDomain(Reservation model) {
        ReservationEntity entity = new ReservationEntity();
        entity.setCid(clientMapper.toEntityFromDomain(model.getClient()));
        entity.setBid(boatMapper.toEntityFromDomain(model.getBoat())); 
        entity.setAmountOfPeople(model.getAmountOfPeople());
        entity.setPrice(model.getPrice());
        entity.setDeposit(model.getDeposit());
        entity.setStartTime(model.getStartTime());
        entity.setEndTime(model.getEndTime());
        return entity;
    }
}
    