package com.java.tp.boat.rental.utils.mappers;

import org.springframework.stereotype.Component;

import com.java.tp.boat.rental.exceptions.boat.BoatDoesNotExistException;
import com.java.tp.boat.rental.exceptions.client.ClientDoesNotExistException;
import com.java.tp.boat.rental.exceptions.reservation.ClientHasNoLicenseException;
import com.java.tp.boat.rental.exceptions.reservation.ReservationForTooManyPeopleException;
import com.java.tp.boat.rental.model.business.Reservation;
import com.java.tp.boat.rental.model.entity.ReservationEntity;
import com.java.tp.boat.rental.model.request.ReservationCreationRequest;
import com.java.tp.boat.rental.model.request.ReservationUpdateRequest;
import com.java.tp.boat.rental.model.response.ReservationResponse;
import com.java.tp.boat.rental.service.BoatService;
import com.java.tp.boat.rental.service.ClientService;

import lombok.Data;

@Data
@Component
public class ReservationMapper implements Mapper<Reservation, ReservationEntity, ReservationCreationRequest, ReservationUpdateRequest, ReservationResponse> {

    /*
     * Mapper interface for converting between different representations of a Reservation.
     * 
     * ReservationRequest -> Reservation (Domain Model) -> ReservationEntity (Database Entity) -> ReservationResponse (API Response)
     */

    private BoatService boatService;
    private ClientService clientService;

    private BoatMapper boatMapper;
    private ClientMapper clientMapper;

    @Override
    public Reservation toDomainFromRequestCreation(ReservationCreationRequest requestCreation) throws ClientHasNoLicenseException, ReservationForTooManyPeopleException, ClientDoesNotExistException, BoatDoesNotExistException {
        Reservation reservation = new Reservation(
            requestCreation.getRid(),
            clientService.getClientById(requestCreation.getCid()),
            boatService.getBoatById(requestCreation.getBid()),
            requestCreation.getAmountOfPeople(),
            requestCreation.getStartTime(),
            requestCreation.getEndTime()
        );
        return reservation;
    }

    @Override
    public Reservation toDomainFromEntity(ReservationEntity entity) throws ClientHasNoLicenseException, ReservationForTooManyPeopleException, ClientDoesNotExistException, BoatDoesNotExistException {
        Reservation reservation = new Reservation(
            entity.getRid(),
            clientService.getClientById(entity.getCid().getCid()),
            boatService.getBoatById(entity.getBid().getBid()),
            entity.getAmountOfPeople(),
            entity.getStartTime(),
            entity.getEndTime()
        );
        return reservation;
    }

    @Override
    public ReservationEntity toEntityFromDomain(Reservation model) {
        ReservationEntity reservationEntity = new ReservationEntity(); // for the id to be generated by the database
        reservationEntity.setCid(clientMapper.toEntityFromDomain(model.getClient()));
        reservationEntity.setBid(boatMapper.toEntityFromDomain(model.getBoat()));
        reservationEntity.setAmountOfPeople(model.getAmountOfPeople());
        reservationEntity.setStartTime(model.getStartTime());
        reservationEntity.setEndTime(model.getEndTime());
        return reservationEntity;
    }

    @Override
    public ReservationResponse toResponseFromDomain(Reservation model) {
        ReservationResponse reservationResponse = new ReservationResponse(
            model.getRid(),
            model.getClient(),
            model.getBoat(),
            model.getAmountOfPeople(),
            model.getReservationStatus().name(),
            model.getStartTime(),
            model.getEndTime()
        );
        return reservationResponse;
    }

    @Override
    public ReservationResponse toResponseFromEntity(ReservationEntity entity) {
        ReservationResponse reservationResponse = new ReservationResponse(
            entity.getRid(),
            clientMapper.toDomainFromEntity(entity.getCid()),
            boatMapper.toDomainFromEntity(entity.getBid()),
            entity.getAmountOfPeople(),
            entity.getStatus().name(),
            entity.getStartTime(),
            entity.getEndTime()
        );
        return reservationResponse;
    }

    @Override
    public ReservationCreationRequest toRequestCreationFromRequestUpdate(ReservationUpdateRequest requestUpdate) {
        ReservationCreationRequest reservationCreationRequest = new ReservationCreationRequest();
        reservationCreationRequest.setRid(requestUpdate.getRid());
        reservationCreationRequest.setCid(requestUpdate.getCid());
        reservationCreationRequest.setBid(requestUpdate.getBid());
        reservationCreationRequest.setAmountOfPeople(requestUpdate.getAmountOfPeople());
        reservationCreationRequest.setStartTime(requestUpdate.getStartTime());
        reservationCreationRequest.setEndTime(requestUpdate.getEndTime());
        return reservationCreationRequest;
    }
}
