spring.application.name=tp.boat.rental
server.port=8080

#H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#create tables automatically
spring.jpa.hibernate.ddl-auto=create

#wait for the hibernate to be done before you execute scripts
spring.jpa.defer-datasource-initialization=true

#to say that the database is an H2Dialect im pretty sure
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#show sql in console
spring.jpa.show-sql=true
spring.h2.console.enabled=true

#Log level configuration
logging.level.root=ERROR
logging.level.com.example=INFO
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO